import {StyleSheet} from 'react-native';
import Color from '../../utils/color';
import {SUITVariable} from '../../utils/text';

const style = StyleSheet.create({
  CategoryItem: {
    alignItems: 'center',
    backgroundColor: Color.white,
    borderColor: Color.gray[300],
    borderRadius: 12,
    borderStyle: 'solid',
    borderWidth: 2,
    color: Color.black,
    display: 'flex',
    flexDirection: 'column',
    fontFamily: SUITVariable.Medium,
    fontSize: 16,
    gap: 12,
    justifyContent: 'center',
    padding: 16,
  },
  CatogoryIcon: {
    alignItems: 'center',
    backgroundColor: Color.brand,
    borderRadius: 60,
    display: 'flex',
    height: 60,
    justifyContent: 'center',
    width: 60,
  },
  PopularSearchItem: {
    alignItems: 'center',
    backgroundColor: Color.white,
    borderColor: Color.gray[300],
    borderRadius: 12,
    borderStyle: 'solid',
    borderWidth: 2,
    color: Color.black,
    display: 'flex',
    flexDirection: 'row',
    fontFamily: SUITVariable.Medium,
    fontSize: 16,
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  PopularSearchItemIndex: {
    color: Color.gray[600],
    fontFamily: SUITVariable.SemiBold,
    fontSize: 20,
    textAlign: 'left',
    width: 12,
  },
  PopularViewList: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    gap: 6,
    marginHorizontal: 16,
  },
  RecentSearchItem: {
    backgroundColor: Color.white,
    borderColor: Color.gray[300],
    borderRadius: 12,
    borderStyle: 'solid',
    borderWidth: 2,
    color: Color.black,
    fontFamily: SUITVariable.Medium,
    fontSize: 16,
    padding: 12,
  },
  Search: {
    gap: 20,
  },
  SearchBar: {
    alignItems: 'center',
    backgroundColor: Color.background,
    display: 'flex',
    flexDirection: 'row',
    gap: 16,
    height: 60,
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    width: '100%',
  },
  SearchResultContent: {
    flex: 1,
  },
  SearchResultImage: {
    backgroundColor: Color.gray[600],
    borderRadius: 6,
    flex: 1,
    height: 128,
    objectFit: 'cover',
    width: '100%',
  },
  SearchResultItem: {
    alignItems: 'center',
    backgroundColor: Color.white,
    borderRadius: 12,
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    gap: 12,
    justifyContent: 'center',
    margin: 8,
    padding: 12,
  },
  SearchResultTitle: {
    fontFamily: SUITVariable.Bold,
    fontSize: 16,
  },
  SearchResultValue: {
    fontFamily: SUITVariable.Medium,
    fontSize: 14,
    paddingBottom: 8,
  },
  SearchResultView: {
    flex: 1,
    paddingHorizontal: 8,
  },
  SearchText: {
    alignItems: 'center',
    backgroundColor: Color.white,
    borderColor: Color.gray[300],
    borderRadius: 12,
    borderStyle: 'solid',
    borderWidth: 2,
    display: 'flex',
    flex: 1,
    flexDirection: 'row',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  SearchTextInput: {
    flex: 1,
    fontFamily: SUITVariable.Medium,
  },
  Title: {
    fontFamily: SUITVariable.Bold,
    fontSize: 20,
    marginLeft: 20,
  },
  View: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    gap: 8,
  },
  ViewList: {
    display: 'flex',
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    marginHorizontal: 16,
  },
});

export default style;
